@SummaProject1Vue_HostAddress = http://localhost:5271

# GET weather forecast
GET {{SummaProject1Vue_HostAddress}}/weatherforecast/
Accept: application/json

###

# POST create user
POST {{SummaProject1Vue_HostAddress}}/users
Content-Type: application/json
Accept: application/json

{
    "username": "newuser",
    "email": "newuser@example.com",
    "dob": "2000-01-01",
    "photo": "photo_url_here"
}

###

# GET user by ID
GET {{SummaProject1Vue_HostAddress}}/users/1
Accept: application/json
